# frozen_string_literal: true

module Clickwrap
  # The canonical description of one offer: which policy revision, which
  # document versions and digests, the exact sentences and link labels, the
  # choice structure, the call to action, who it was issued to, and when it
  # stops being valid.
  #
  # This exists because "the database says version 3" is a weak claim. It says
  # what the row contains now, not what was on screen then. A manifest is
  # generated by the server at render, signed, and verified again at submit
  # against the current immutable rows — so a deploy between GET and POST can
  # never cause the server to record a version the person was not offered.
  #
  # What it proves is bounded, and the receipt says so: the server generated and
  # accepted this particular offer. It does not prove the person read the
  # document, understood it, saw particular pixels, or received an interface
  # that any given jurisdiction would consider adequate.
  class PresentationManifest
    SIGNING_PURPOSE = "clickwrap/presentation"

    attr_reader :attributes

    def initialize(attributes)
      @attributes = deep_stringify(attributes).freeze
      # Computed here rather than memoized on first use: the object is frozen
      # below, and a manifest that could still change after construction is not
      # a manifest anything should be bound to.
      @digest = Digest.digest_canonical(
        @attributes, algorithm: Clickwrap.config.digest_canonical_receipts_with.to_s
      ).freeze
      freeze
    end

    class << self
      def build(policy:, revision_digest:, statements:, submit_button_text:, locale:,
                actor_reference: nil, actor_type: nil, tenant_key: nil, subject_key: nil,
                subject_fingerprint: nil, registration_flow_id: nil,
                capture_channel: "web_browser", issued_at: nil, expires_at: nil, nonce: nil)
        issued_at ||= Clickwrap.now
        expires_at ||= issued_at + Clickwrap.config.presentation_valid_for

        new(
          "schema" => Clickwrap::CANONICAL_SCHEMA_VERSION,
          "policy" => { "key" => policy.key, "revision" => revision_digest },
          "statements" => statements,
          "submit_button_text" => submit_button_text,
          "locale" => locale.to_s,
          "actor" => { "reference" => actor_reference, "type" => actor_type }.compact.presence,
          "registration_flow_id" => registration_flow_id,
          "tenant_key" => tenant_key,
          "subject" => { "reference" => subject_key, "fingerprint" => subject_fingerprint }.compact.presence,
          "capture_channel" => capture_channel.to_s,
          "issued_at" => Receipt.format_time(issued_at),
          "expires_at" => Receipt.format_time(expires_at),
          "nonce" => nonce || SecureRandom.uuid,
          "gem_version" => Clickwrap::VERSION,
          "application_version" => Clickwrap.config.resolved_application_version,
          "template_version" => Clickwrap.config.resolved_template_version
        )
      end

      # Reads a token back into a manifest. Every failure here is the same kind
      # of failure — the browser handed us something we did not sign, or signed
      # too long ago — so they all raise PresentationInvalid rather than leaking
      # which specific check tripped.
      def from_token(token)
        raise PresentationInvalid, "No presentation token was submitted" if token.blank?

        payload = verifier.verified(token, purpose: SIGNING_PURPOSE)

        raise PresentationInvalid, "The presentation token could not be verified" if payload.nil?

        new(payload)
      rescue ActiveSupport::MessageVerifier::InvalidSignature
        raise PresentationInvalid, "The presentation token could not be verified"
      end

      def verifier
        @verifier ||= build_verifier
      end

      def reset_verifier!
        @verifier = nil
      end

      private

      def build_verifier
        secret =
          if defined?(::Rails) && ::Rails.application
            ::Rails.application.key_generator.generate_key("clickwrap/presentation-manifest", 32)
          else
            ENV.fetch("CLICKWRAP_PRESENTATION_SECRET") do
              raise ConfigurationError,
                    "Clickwrap needs a signing secret for presentation tokens. Inside Rails it " \
                    "derives one from secret_key_base; outside Rails, set " \
                    "CLICKWRAP_PRESENTATION_SECRET."
            end
          end

        ActiveSupport::MessageVerifier.new(secret, digest: "SHA256", serializer: JSON)
      end
    end

    def [](key) = attributes[key.to_s]

    def policy_key = attributes.dig("policy", "key")
    def revision_digest = attributes.dig("policy", "revision")
    def statements = attributes["statements"] || []
    def submit_button_text = attributes["submit_button_text"]
    def locale = attributes["locale"]
    def nonce = attributes["nonce"]
    def actor_reference = attributes.dig("actor", "reference")
    def registration_flow_id = attributes["registration_flow_id"]
    def tenant_key = attributes["tenant_key"]
    def subject_key = attributes.dig("subject", "reference")
    def subject_fingerprint = attributes.dig("subject", "fingerprint")
    def capture_channel = attributes["capture_channel"]
    def issued_at = parse_time(attributes["issued_at"])
    def expires_at = parse_time(attributes["expires_at"])

    def statement(key)
      statements.find { |statement| statement["key"] == key.to_s }
    end

    def expired?(at = Clickwrap.now) = expires_at.nil? || expires_at <= at

    # Computed in the constructor, before the object freezes. Lazy memoization
    # would raise on a frozen manifest, and recomputing on every call would
    # canonicalize the whole body each time it is read — which happens on every
    # render and every capture.
    attr_reader :digest

    def to_token
      self.class.verifier.generate(attributes, purpose: SIGNING_PURPOSE, expires_at: expires_at)
    end

    def to_h = attributes

    def to_s = "presentation of #{policy_key} (#{nonce})"

    private

    def parse_time(value)
      return nil if value.blank?

      Time.parse(value).utc
    rescue ArgumentError
      nil
    end

    def deep_stringify(value)
      case value
      when Hash then value.to_h { |key, nested| [key.to_s, deep_stringify(nested)] }
      when Array then value.map { |element| deep_stringify(element) }
      when Symbol then value.to_s
      else value
      end
    end
  end
end
